[package]
name = "onnx-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
backend-autodiff-wgpu = ["burn-autodiff", "burn-wgpu"]

[dev-dependencies]
burn = { path = "../../burn" }
burn-ndarray = { path = "../../burn-ndarray" }
serde = { workspace = true }
float-cmp = { workspace = true }

[build-dependencies]
burn-import = { path = "../" }

[dependencies]
burn-autodiff = { path = "../../burn-autodiff", version = "0.19.0", default-features = false, optional = true }
burn-wgpu = { path = "../../burn-wgpu", version = "0.19.0", optional = true, default-features = false }
