[package]
authors = ["laggui <lagrange.guillaume.1@gmail.com>"]
edition.workspace = true
license.workspace = true
name = "custom-image-dataset"
description = "Example implementation for loading a custom image dataset from disk"
publish = false
version.workspace = true

[lints]
workspace = true

[features]
default = ["burn/std", "burn/tui"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu", "burn/fusion"]
metal = ["burn/metal", "burn/fusion"]

[dependencies]
# Disable autotune default for now (convolutions not optimized)
burn = { path = "../../crates/burn", features = [
    "train",
    "vision",
    "network",
], default-features = false }


# File download
flate2 = { workspace = true }
tar = "0.4.44"
