[default]
extend-ignore-identifiers-re = ["ratatui", "Ratatui", "NdArray*", "ND"]

[default.extend-identifiers]
UE8M0 = "UE8M0"
ue8m0 = "ue8m0"

[files]
extend-exclude = [
    "*.onnx",
    "assets/ModuleSerialization.xml",
    "examples/image-classification-web/src/model/label.txt",
]

[default.extend-words]
# Don't correct "arange" which is intentional
arange = "arange"
