[package]
name = "burn-complex"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
num-complex = { version = "0.4.6" }
burn-tensor = { path = "../burn-tensor", version = "0.19.0", default-features = false }

[lints]
workspace = true
